Python Program to Design a Hopfield Network which Stores 4 Vectors
Small Information

A Hopfield Network is a type of recurrent neural network used for:

Associative memory

Pattern storage

Pattern recovery


It stores patterns (vectors) and recalls them even if noisy or incomplete input is given.

The network uses:

Bipolar values (1 and -1)

Symmetric weight matrix

Energy minimization concept

In [1]:
import numpy as np

# Define 4 bipolar vectors
V1 = np.array([1, -1, 1, -1])
V2 = np.array([-1, 1, -1, 1])
V3 = np.array([1, 1, -1, -1])
V4 = np.array([-1, -1, 1, 1])

# Store vectors in list
patterns = [V1, V2, V3, V4]

# Number of neurons
n = len(V1)

# Initialize weight matrix
W = np.zeros((n, n))

# Training Hopfield Network
for p in patterns:

    W += np.outer(p, p)

# Remove self connections
np.fill_diagonal(W, 0)

print("Weight Matrix:\n")
print(W)

# Test pattern (noisy input)
test = np.array([1, -1, 1, -1])

print("\nTest Pattern:")
print(test)

# Recall process
net = np.dot(W, test)

# Activation function
output = np.where(net >= 0, 1, -1)

print("\nRecovered Pattern:")
print(output)

Weight Matrix:

[[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]

Test Pattern:
[ 1 -1  1 -1]

Recovered Pattern:
[ 1 -1  1 -1]


Explanation
1. Store Patterns

Four bipolar vectors are stored in the network.

Example:

[1 -1 1 -1]
2. Weight Matrix Calculation

Weights are calculated using outer products:

W=∑X
i
	​

X
i
T
	​


Where:

X
i
	​

 = stored pattern
3. Remove Self Connections

Diagonal values are set to zero because neurons do not connect to themselves.

4. Recall Process

The network recalls stored patterns using:

Y=sign(WX)

Where:

W = weight matrix
X = input pattern
Applications
Associative memory
Pattern recognition
Image restoration
Noise removal
AI memory systems
Advantages
Stores multiple patterns
Noise tolerant
Simple implementation
Fast recall mechanism
Conclusion

The Hopfield Network stores and recalls patterns using a recurrent neural architecture and weight matrix generated from stored vectors.