Python Program to Recognize Numbers using 5×3 Matrix Neural Network
Small Information

In this program, numbers are represented using a 5 × 3 binary matrix.

1 → Valid point (filled pixel)
0 → Invalid point (empty pixel)

The neural network is trained to recognize numbers:

0
1
2
3

Each matrix is converted into a vector and matched with trained patterns.

In [1]:
import numpy as np

# Training patterns for numbers 0,1,2,3 using 5x3 matrix

patterns = {

    '0': np.array([
        [1,1,1],
        [1,0,1],
        [1,0,1],
        [1,0,1],
        [1,1,1]
    ]),

    '1': np.array([
        [0,1,0],
        [1,1,0],
        [0,1,0],
        [0,1,0],
        [1,1,1]
    ]),

    '2': np.array([
        [1,1,1],
        [0,0,1],
        [1,1,1],
        [1,0,0],
        [1,1,1]
    ]),

    '3': np.array([
        [1,1,1],
        [0,0,1],
        [0,1,1],
        [0,0,1],
        [1,1,1]
    ])
}

# Convert matrices into vectors
training_data = {}

for key, value in patterns.items():
    training_data[key] = value.flatten()

# Test pattern
test = np.array([
    [1,1,1],
    [0,0,1],
    [1,1,1],
    [1,0,0],
    [1,1,1]
])

test_vector = test.flatten()

# Recognition using minimum distance
min_distance = float('inf')
recognized_number = None

for number, vector in training_data.items():

    distance = np.sum((test_vector - vector) ** 2)

    if distance < min_distance:
        min_distance = distance
        recognized_number = number

# Output
print("Test Pattern:\n")
print(test)

print("\nRecognized Number is:", recognized_number)

Test Pattern:

[[1 1 1]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [1 1 1]]

Recognized Number is: 2
